[workspace]
resolver = "2"
members = [
    "algebra-core",
    "concurrent-primitives",
    "cardano-chain-sync",
    "cardano-mempool-sync",
    "cardano-submit-api",
    "spectrum-offchain",
    "spectrum-offchain-cardano",
    "spectrum-cardano-lib",
    "cardano-explorer",
    "bloom-offchain",
    "bloom-offchain-cardano",
    "green-order-cardano-agent",
    "bloom-derivation",
    "spectrum-streaming",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
