import { Emulator, generateSeedPhrase, getAddressDetails, Lucid } from "npm:@lucid-evolution/lucid@0.3.53";

type PreparedWallet = {
  role: "batcher" | "deployment";
  network: "Preprod";
  address: string;
  paymentKeyHash: string;
  seedPhrase: string;
  requestedAda: number;
};

type PreparedWallets = {
  createdAt: string;
  wallets: PreparedWallet[];
};

const statePath = Deno.env.get("WALLET_STATE_PATH")?.trim() || ".state/preprod-wallets.json";
const envPath = Deno.env.get("WALLET_ENV_PATH")?.trim() || ".env.wallets";
const forceNewWallets = Deno.env.get("FORCE_NEW_WALLETS")?.trim() === "1";

const requestedAda = {
  batcher: Number(Deno.env.get("E2E_BATCHER_REQUESTED_ADA")?.trim() || "400"),
  deployment: 20,
} as const;

await Deno.mkdir(dirname(statePath), { recursive: true });
await Deno.mkdir(dirname(envPath), { recursive: true });

const existing = forceNewWallets ? undefined : await readExisting(statePath);
const wallets = existing ?? {
  createdAt: new Date().toISOString(),
  wallets: [
    await deriveWallet("batcher", generateSeedPhrase(), requestedAda.batcher),
    await deriveWallet("deployment", generateSeedPhrase(), requestedAda.deployment),
  ],
};

await Deno.writeTextFile(statePath, `${JSON.stringify(wallets, null, 2)}\n`, { mode: 0o600 });
await Deno.writeTextFile(envPath, renderEnv(wallets), { mode: 0o600 });

for (const wallet of wallets.wallets) {
  console.log(`${wallet.role.toUpperCase()}_ADDRESS=${wallet.address}`);
  console.log(`${wallet.role.toUpperCase()}_PAYMENT_KEY_HASH=${wallet.paymentKeyHash}`);
  console.log(`${wallet.role.toUpperCase()}_REQUESTED_ADA=${wallet.requestedAda}`);
}
console.log(`WALLET_STATE_PATH=${statePath}`);
console.log(`WALLET_ENV_PATH=${envPath}`);

function dirname(path: string): string {
  const index = path.lastIndexOf("/");
  return index < 0 ? "." : path.slice(0, index) || "/";
}

async function readExisting(path: string): Promise<PreparedWallets | undefined> {
  try {
    return JSON.parse(await Deno.readTextFile(path)) as PreparedWallets;
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
}

async function deriveWallet(
  role: PreparedWallet["role"],
  seedPhrase: string,
  ada: number,
): Promise<PreparedWallet> {
  const lucid = await Lucid(new Emulator([]), "Preprod");
  lucid.selectWallet.fromSeed(seedPhrase, { addressType: "Enterprise" });
  const address = await lucid.wallet().address();
  const paymentKeyHash = getAddressDetails(address).paymentCredential?.hash;
  if (!paymentKeyHash) {
    throw new Error(`failed to derive ${role} payment key hash`);
  }
  return {
    role,
    network: "Preprod",
    address,
    paymentKeyHash,
    seedPhrase,
    requestedAda: ada,
  };
}

function renderEnv(wallets: PreparedWallets): string {
  const batcher = wallets.wallets.find((wallet) => wallet.role === "batcher");
  const deployment = wallets.wallets.find((wallet) => wallet.role === "deployment");
  if (!batcher || !deployment) throw new Error("prepared wallet set is incomplete");

  return [
    `# Generated by 00-prepare-preprod-wallets.ts at ${wallets.createdAt}`,
    "# Do not commit this file.",
    `FUNDED_WALLET_SEED=${batcher.seedPhrase}`,
    `OPERATOR_KEY_HASH_HEX=${batcher.paymentKeyHash}`,
    `BATCHER_ADDRESS=${batcher.address}`,
    `DEPLOYMENT_WALLET_SEED=${deployment.seedPhrase}`,
    `DEPLOYMENT_ADDRESS=${deployment.address}`,
    "",
  ].join("\n");
}
