import { CML, Lucid } from "npm:@lucid-evolution/lucid@0.3.53";
import { submitSignedTx } from "./src/lucid.ts";
import { assertWritableAgentConfig, resolveAgentConfigPath } from "./src/operator_config.ts";
import { loadPreprodEnv, lovelaceToAda, preprodProvider } from "./src/provider.ts";

type OperatorState = {
  operatorKey: string;
  operatorKeyHashHex: string;
  collateralAddress: string;
  fundingAddresses: string[];
  fundingTxHash?: string;
};

const statePath = ".state/preprod-operator.json";
const envPath = ".env.operator";
const agentConfigPath = resolveAgentConfigPath(Deno.env.get("AGENT_CONFIG_PATH"));
const operatorFundingLovelace = 50_000_000n;

await loadPreprodEnv();
await Deno.mkdir(".state", { recursive: true });

const operator = await loadOrCreateOperator();
await writeOperatorEnv(operator);
await writeAgentConfig(operator.operatorKey);
const provider = preprodProvider();

if (operator.fundingTxHash && await hasUsableOperatorFunding(operator)) {
  console.log(`operator funding already submitted: ${operator.fundingTxHash}`);
  await printBalances(operator);
  Deno.exit(0);
}

const fundedWalletSeed = requiredEnv("FUNDED_WALLET_SEED");
const lucid = await Lucid(provider, "Preprod");
lucid.selectWallet.fromSeed(fundedWalletSeed, { addressType: "Enterprise" });

const batcherAddress = await lucid.wallet().address();
if (batcherAddress !== requiredEnv("BATCHER_ADDRESS")) {
  throw new Error(`funding seed derives ${batcherAddress}, expected ${requiredEnv("BATCHER_ADDRESS")}`);
}

const tx = await lucid
  .newTx()
  .pay.ToAddress(operator.collateralAddress, { lovelace: 10_000_000n })
  .pay.ToAddress(operator.fundingAddresses[0], { lovelace: operatorFundingLovelace })
  .pay.ToAddress(operator.fundingAddresses[1], { lovelace: operatorFundingLovelace })
  .pay.ToAddress(operator.fundingAddresses[2], { lovelace: operatorFundingLovelace })
  .pay.ToAddress(operator.fundingAddresses[3], { lovelace: operatorFundingLovelace })
  .complete();

const txHash = await submitSignedTx(await tx.sign.withWallet().complete());
operator.fundingTxHash = txHash;
await Deno.writeTextFile(statePath, `${JSON.stringify(operator, null, 2)}\n`, { mode: 0o600 });
console.log(`operator_funding_tx=${txHash}`);
await waitForOperatorFunding(operator);
await printBalances(operator);

async function loadOrCreateOperator(): Promise<OperatorState> {
  try {
    return JSON.parse(await Deno.readTextFile(statePath)) as OperatorState;
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error;
  }

  const key = CML.Bip32PrivateKey.generate_ed25519_bip32();
  const operatorKey = key.to_bech32();
  const publicKey = key.to_public();
  const mainHash = publicKey.to_raw_key().hash();
  const mainCred = CML.Credential.new_pub_key(mainHash);
  const collateralAddress = CML.EnterpriseAddress.new(0, mainCred).to_address().to_bech32(undefined);
  const fundingAddresses = [1, 2, 3, 4].map((index) => {
    const childHash = publicKey.derive(index).to_raw_key().hash();
    return CML.BaseAddress.new(
      0,
      CML.Credential.new_pub_key(mainHash),
      CML.Credential.new_pub_key(childHash),
    ).to_address().to_bech32(undefined);
  });

  const state = {
    operatorKey,
    operatorKeyHashHex: mainHash.to_hex(),
    collateralAddress,
    fundingAddresses,
  };
  await Deno.writeTextFile(statePath, `${JSON.stringify(state, null, 2)}\n`, { mode: 0o600 });
  return state;
}

async function writeOperatorEnv(operator: OperatorState): Promise<void> {
  await Deno.writeTextFile(
    envPath,
    [
      "# Generated by 07-prepare-operator-funding.ts.",
      "# Do not commit this file.",
      `OPERATOR_KEY_HASH_HEX=${operator.operatorKeyHashHex}`,
      `OPERATOR_COLLATERAL_ADDRESS=${operator.collateralAddress}`,
      `OPERATOR_FUNDING_ADDRESS_1=${operator.fundingAddresses[0]}`,
      `OPERATOR_FUNDING_ADDRESS_2=${operator.fundingAddresses[1]}`,
      `OPERATOR_FUNDING_ADDRESS_3=${operator.fundingAddresses[2]}`,
      `OPERATOR_FUNDING_ADDRESS_4=${operator.fundingAddresses[3]}`,
      "",
    ].join("\n"),
    { mode: 0o600 },
  );
}

async function writeAgentConfig(operatorKey: string): Promise<void> {
  assertWritableAgentConfig(agentConfigPath, { partialE2e: Deno.env.get("PARTIAL_E2E") === "1" });
  const config = JSON.parse(await Deno.readTextFile(agentConfigPath));
  config.operatorKey = operatorKey;
  config.minOperatorFundingLovelace = Number(operatorFundingLovelace);
  config.node = { ...config.node, path: requiredEnv("CARDANO_NODE_SOCKET_PATH"), magic: 1 };
  config.networkId = 0;
  await Deno.writeTextFile(agentConfigPath, `${JSON.stringify(config, null, 2)}\n`);
  console.log(`Updated agent config ${agentConfigPath}`);
}

async function hasUsableOperatorFunding(operator: OperatorState): Promise<boolean> {
  const collateral = await provider.getUtxos(operator.collateralAddress);
  const hasCollateral = collateral.some((utxo) =>
    !Object.keys(utxo.assets).some((unit) => unit !== "lovelace") && utxo.assets.lovelace === 10_000_000n
  );
  const funded = await Promise.all(operator.fundingAddresses.map((address) => provider.getUtxos(address)));
  const hasFunding = funded.every((utxos) =>
    utxos.some((utxo) =>
      !Object.keys(utxo.assets).some((unit) => unit !== "lovelace") &&
      (utxo.assets.lovelace ?? 0n) >= operatorFundingLovelace
    )
  );
  return hasCollateral && hasFunding;
}

async function waitForOperatorFunding(operator: OperatorState): Promise<void> {
  for (let attempt = 0; attempt < 60; attempt++) {
    if (await hasUsableOperatorFunding(operator)) return;
    await new Promise((resolve) => setTimeout(resolve, 5_000));
  }
  throw new Error("operator funding was not observed on preprod");
}

async function printBalances(operator: OperatorState): Promise<void> {
  for (
    const [label, address] of [
      ["collateral", operator.collateralAddress],
      ...operator.fundingAddresses.map((address, index) => [`funding${index + 1}`, address] as const),
    ] as const
  ) {
    const utxos = await provider.getUtxos(address);
    const lovelace = utxos.reduce((sum, utxo) => sum + (utxo.assets.lovelace ?? 0n), 0n);
    console.log(`${label}: ${lovelaceToAda(lovelace)} tADA ${address}`);
  }
}

function requiredEnv(name: string): string {
  const value = Deno.env.get(name)?.trim();
  if (!value) throw new Error(`Set ${name}`);
  return value;
}
